### PR TITLE
Adds F# quickstart

### PR DESCRIPTION
**Pull request by bclehmann**
Mentioned in https://github.com/ScottPlot/ScottPlot/issues/1276

Worth noting that although WPF and WinForms "support" F# in that it won't not work, Avalonia seems to support it as a first-class language. I think several Avalonia contributors are also active in the F# community. It may be worth considering a quickstart (or even demo) for F# on Avalonia, but that probably would require someone who's fluent with F#.

### CODE REVIEW

**Comment by bclehmann** [comment]
image

**Comment by swharden** [comment]
Awesome @bclehmann, thanks!

**Comment by FoggyFinder** [comment]
> Worth noting that although WPF and WinForms "support" F# in that it won't not work, 

@bclehmann why not? I've wrote couple of WPF-app fully with F#. Well, all of them were relatively small (no more than 8-10 pages) but still I see no reason why ScottPlot won't work there. I didn't try it by myself though.

**Comment by bclehmann** [comment]
They will still work, but since F# isn't actively supported you could be liable to run into issues you wouldn't have in C#.

Similar to how C++/CLI "works" but isn't officially supported anymore and it can be a real pain to use.

Additionally (for WPF at least), I think the F# community recommends Elmish, rather than raw WPF.

**Pull request merged**
